"""initial db

Revision ID: c348688b556c
Revises: 
Create Date: 2023-10-06 17:34:31.758813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c348688b556c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('session_id', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_Users_session_id'), 'Users', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_session_id'), table_name='Users')
    op.drop_column('Users', 'session_id')
    # ### end Alembic commands ###
